In [78]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import os

In [79]:
pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\naufi\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\naufi\anaconda3\lib\site-packages (from kagglehub) (0.1.30)
Requirement already satisfied: packaging in c:\users\naufi\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\naufi\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\naufi\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\naufi\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\naufi\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\naufi\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\naufi\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\naufi\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\naufi\anaconda3\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\users\naufi\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [80]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sriharshaeedala/airline-delay")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\naufi\.cache\kagglehub\datasets\sriharshaeedala\airline-delay\versions\1

In [81]:
file_path = os.path.join(path, "Airline_Delay_Cause.csv")
df = pd.read_csv(file_path)
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171666 entries, 0 to 171665
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 171666 non-null  int64
 1   month                171666 non-null  int64
 2   carrier              171666 non-null  object
 3   carrier_name         171666 non-null  object
 4   airport              171666 non-null  object
 5   airport_name         171666 non-null  object
 6   arr_flights          171426 non-null  float64
 7   arr_del15            171223 non-null  float64
 8   carrier_ct           171426 non-null  float64
 9   weather_ct           171426 non-null  float64
 10  nas_ct               171426 non-null  float64
 11  security_ct          171426 non-null  float64
 12  late_aircraft_ct     171426 non-null  float64
 13  arr_cancelled        171426 non-null  float64
 14  arr_diverted         171426 non-null  float64
 15  arr_delay            171426 non-null  float64
 16  carrier_delay        171426 non-null  float64
 17  weather_delay        171426 non-null  float64
 18  nas_delay            171426 non-null  float64
 19  security_delay       171426 non-null  float64
 20  late_aircraft_delay  171426 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 27.5+ MB
None

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

# Dataset

This dataset provides detailed information on flight arrivals and delays for U.S. airports, categorized by carriers.
- `year`: The year of the data.
- `month`: The month of the data.
- `carrier`: Carrier code.
- `carrier_name`: Carrier name.
- `airport`: Airport code.
- `arr_flights`: Number of arriving flights.
- `arr_del15`: Number of flights delayed by 15 minutes or more.
- `carrier_ct`: Carrier count (delay due to the carrier).
- `weather_ct`: Weather count (delay due to weather).
- `nas_ct`: NAS (National Airspace System) count (delay due to the NAS).
- `security_ct`: Security count (delay due to security).
- `late_aircraft_ct`: Late aircraft count (delay due to late aircraft arrival).
- `arr_cancelled`: Number of flights canceled.
- `arr_diverted`: Number of flights diverted.
- `arr_delay`: Total arrival delay in minutes.
- `carrier_delay`: Delay in minutes attributed to the carrier.
- `weather_delay`: Delay in minutes attributed to weather.
- `nas_delay`: Delay in minutes attributed to the NAS.
- `security_delay`: Delay in minutes attributed to security.
- `late_aircraft_delay`: Delay in minutes attributed to late aircraft arrival.

In [82]:
# Data Cleaning
print(df.isna().sum())

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights            240
arr_del15              443
carrier_ct             240
weather_ct             240
nas_ct                 240
security_ct            240
late_aircraft_ct       240
arr_cancelled          240
arr_diverted           240
arr_delay              240
carrier_delay          240
weather_delay          240
nas_delay              240
security_delay         240
late_aircraft_delay    240
dtype: int64

In [83]:
# We drop the Null entries in the `arr_flights` column.
df = df.dropna(subset=['arr_flights']).reset_index(drop=True)
print(df.isna().sum())

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights              0
arr_del15              203
carrier_ct               0
weather_ct               0
nas_ct                   0
security_ct              0
late_aircraft_ct         0
arr_cancelled            0
arr_diverted             0
arr_delay                0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
dtype: int64

In [84]:
# We check the Null entries in `arr_del15`
# df.columns
# arr_del15_columns = ['carrier_ct', 'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct']
# print(df[df['arr_del15'].isna()][arr_del15_columns].sum())
# This implies it is reasonable to fill the Null values in the `arr_del15` with zero.
df = df.fillna(0)
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [85]:
# We check that `arr_del15` is the sum of the columns listed in `arr_del15_columns`.
arr_del15_columns = ['carrier_ct', 'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct']
arr_delay_columns = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']
df[arr_del15_columns] = np.ceil(df[arr_del15_columns])
df['arr_del15'] = df[arr_del15_columns].sum(axis=1)
df['arr_delay'] = df[arr_delay_columns].sum(axis=1)
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,15.0,3.0,2.0,...,0.0,6.0,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,12.0,2.0,1.0,...,0.0,8.0,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,12.0,3.0,2.0,...,0.0,5.0,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,14.0,4.0,3.0,...,0.0,2.0,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,23.0,8.0,0.0,...,0.0,12.0,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [91]:
for x in df['carrier_name'].unique():
    print(f'{x} has carrier names {df[df['carrier_name'] == x]['carrier'].unique()}')

Endeavor Air Inc. has carrier names ['9E']
American Airlines Inc. has carrier names ['AA']
Alaska Airlines Inc. has carrier names ['AS']
JetBlue Airways has carrier names ['B6']
Delta Air Lines Inc. has carrier names ['DL']
Frontier Airlines Inc. has carrier names ['F9']
Allegiant Air has carrier names ['G4']
Hawaiian Airlines Inc. has carrier names ['HA']
Envoy Air has carrier names ['MQ']
Spirit Air Lines has carrier names ['NK']
PSA Airlines Inc. has carrier names ['OH']
SkyWest Airlines Inc. has carrier names ['OO']
United Air Lines Inc. has carrier names ['UA']
Southwest Airlines Co. has carrier names ['WN']
Republic Airline has carrier names ['YX']
Horizon Air has carrier names ['QX']
Mesa Airlines Inc. has carrier names ['YV']
ExpressJet Airlines LLC has carrier names ['EV']
ExpressJet Airlines Inc. has carrier names ['EV']
Virgin America has carrier names ['VX']
US Airways Inc. has carrier names ['US']
AirTran Airways Corporation has carrier names ['FL']
American Eagle Airlines Inc. has carrier names ['MQ']